<Project>

  <!-- Los archivos intermedios (obj/bin) se generan en la ruta estándar relativa al proyecto,
       lo que garantiza compatibilidad en todos los sistemas operativos (Windows, Linux, macOS). -->
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)\bin\</BaseOutputPath>
  </PropertyGroup>

</Project>
